version: "3.6"

services:
  dhis2-core:
    image: tons/dhis2-core:2.37-SNAPSHOT
    ports:
      - 8080:9080
    environment:
      JAVA_TOOL_OPTIONS: "-Djetty.host=0.0.0.0"
    volumes:
      - ./config/dhis.conf:/opt/dhis2/dhis.conf:rw

  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSOWRD: dhis

  dhis2-base:
    image: tons/dhis2-base
    build:
      context: .
      dockerfile: Dockerfile.base
